In [1]:
import pandas as pd
import os

df = pd.DataFrame([[1,2],[1,2]])

In [9]:
from datetime import datetime

In [2]:
from sensor.utils.main_utils import read_yaml_file

In [2]:
file_path="/home/avnish/iNeuron_Private_Intelligence_Limited/industry_ready_project/live_class/sensor-fault-detection/config/schema.yaml"

In [4]:
schema_config = read_yaml_file(file_path=file_path)

In [7]:
len(schema_config['columns'])==len(df.columns)

164

In [10]:
from scipy.stats import ks_2samp

In [9]:
import numpy as np

In [18]:
d1 = np.arange(100,200)
d2 = np.arange(10)

In [19]:
d1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [20]:
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
d1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [28]:
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
test = ks_2samp(d1,d2)

In [30]:
round(test.pvalue)

0

In [1]:
traing_file_path = "./artifact/11_08_2022_23_08_46/data_ingestion/ingested/train.csv"

In [2]:
test_file_path = "artifact/11_08_2022_23_08_46/data_ingestion/ingested/test.csv"

In [3]:
import pandas as pd

In [4]:
train_df = pd.read_csv(traing_file_path)
test_df = pd.read_csv(test_file_path)

In [5]:
train_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [6]:
test_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [7]:
from sensor.utils.main_utils import write_yaml_file

In [8]:

def get_drift_report(base_df,current_df,threshold=0.05):
    report ={}
    for column in base_df.columns:
        d1 = base_df[column]
        d2  = current_df[column]
        is_same_dist = ks_2samp(d1,d2)
        if threshold<=is_same_dist.pvalue:
            is_found=False
        else:
            is_found = True 
        report.update({column:{
            "p_value":float(is_same_dist.pvalue),
            "drift_status":is_found
            
            }})
    return report



In [11]:
drift_report = get_drift_report(train_df,test_df)

In [12]:
drift_report

{'class': {'p_value': 0.9991748491981378, 'drift_status': False},
 'aa_000': {'p_value': 0.6842958417494523, 'drift_status': False},
 'ab_000': {'p_value': 1.0, 'drift_status': False},
 'ac_000': {'p_value': 0.46187470035376, 'drift_status': False},
 'ad_000': {'p_value': 0.8003356336354227, 'drift_status': False},
 'ae_000': {'p_value': 0.9999947765853102, 'drift_status': False},
 'af_000': {'p_value': 0.9999975889466275, 'drift_status': False},
 'ag_000': {'p_value': 0.998951316200958, 'drift_status': False},
 'ag_001': {'p_value': 0.999904915980834, 'drift_status': False},
 'ag_002': {'p_value': 0.7903488032262538, 'drift_status': False},
 'ag_003': {'p_value': 0.6887311260596665, 'drift_status': False},
 'ag_004': {'p_value': 0.39919893576231646, 'drift_status': False},
 'ag_005': {'p_value': 0.552527110657778, 'drift_status': False},
 'ag_006': {'p_value': 0.3491276285535705, 'drift_status': False},
 'ag_007': {'p_value': 0.18804738551081024, 'drift_status': False},
 'ag_008': {'p

In [13]:
write_yaml_file(file_path=os.path.join(os.getcwd(),"report.yaml"),content=drift_report,replace=True)

In [14]:
d1 = train_df['class']
d2  = test_df['class']
ks_2samp(d1,d2)

KstestResult(statistic=0.004833747812471256, pvalue=0.9991748491981378)

KstestResult(statistic=0.009896540089462558, pvalue=0.6183763526162667)

In [1]:
from sensor.ml.model.estimator import TargetValueMapping

In [3]:
TargetValueMapping().to_dict()

{'neg': 0, 'pos': 1}

In [4]:
TargetValueMapping().reverse_mapping()

{0: 'neg', 1: 'pos'}

In [9]:
from sensor.ml.model.estimator import TargetValueMapping

ImportError: cannot import name 'TargetValueMapping' from 'sensor.ml.model.estimator' (c:\Users\Akash\Documents\industry_ready_projects\projects\sensor-fault-detection\sensor\ml\model\estimator.py)